saltstack-formulas/zabbix-formula

zabbix/files/default/etc/zabbix/zabbix_agentd.conf.jinja
Hi,
due to this documented behaviour in Zabbix active agent auto-registration, always setting the ListenIP parameter in zabbix_agentd.conf to default 0.0.0.0 can be problematic:
>Active agent auto-registration also supports the monitoring of added hosts with passive checks. When the active agent asks for checks, providing it has the 'ListenIP' or 'ListenPort' configuration parameters defined in the configuration file, these are sent along to the server. (If multiple IP addresses are specified, the first one is sent to the server.)
https://www.zabbix.com/documentation/2.2/manual/discovery/auto_registration
Active agent auto-registration reads the explicitly set value from ListenIP and sends it to the Zabbix server, which will set 0.0.0.0 as the agent interface during auto-registration. …
=> ListenIP being set to default 0.0.0.0

zabbix/server/init.sls, zabbix/server/repo.sls
The code removed in this commit was written to ensure that the
installation of the zabbix-server package does not pull in the
mysql-server package via Recommends on Debian. The way it was written
did, however, disable the installation of *any* recommended package
globally and outwith the scope of this formula.
One problematic aspect of this approach is that it requires users to use
at least salt 2015.5.0 as setting "install_recommends" was not supported
before.
This fixes #19
=> Specifically disable Recommends for zabbix-server

pillar.example
Since #21 removed hardcoded value, we'll put it back with pillar.
Historically `LogFileSize` was set as 0 both in deb package's and salt's version of config.
=> Added default value for LogFileSize (agent option)

zabbix/agent/init.sls, zabbix/frontend/init.sls, zabbix/map.jinja, zabbix/proxy/init.sls, zabbix/server/init.sls
Hi there,
Zabbix also comes with two cli tools: zabbix_sender and zabbix_get. Sender belongs with the agent, get belongs with (at least) server and proxy.
This PR installs updates the formula to have zabbix_sender installed as part of the zabbix_agent state, zabbix_get as part of the server and proxy states.
=> Added packages zabbix_sender to agent, zabbix_get to server and proxy

zabbix/map.jinja, zabbix/users.sls
Quick addition for the Zabbix-agent on OpenBSD
and a fix to keep `/nonexistent` nonexistent on the BSD's ;)
=> OpenBSD-support (for the agent only)

zabbix/map.jinja
Template for `agentd.conf` failed to render because there 
was no `'version_repo'` key for FreeBSD in `map.jinja`.
=> add "version_repo" for FreeBSD to fix agentd.conf template

zabbix/map.jinja
When installing/checking the zabbix packages in RedHat/CentOS, the state fails since the state expects a dictionary. Edited map.jinja to correct issue #33
=> Fix packages dictionary for RedHat

zabbix/map.jinja
On RedHat i get this error `Rendering SLS 'base:zabbix.server' failed: Jinja variable 'dict object' has no attribute 'logfile'`
This change will fix it by setting default values for logfile and pidfile like for Debian and others.
=> Add missing logile & pidfile entries in map.jinja

zabbix/frontend/conf.sls, zabbix/server/conf.sls
Corrects errors:
```
[ERROR   ] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'pkg'
[CRITICAL] Rendering SLS 'base:zabbix.server.conf' failed: Jinja variable 'dict object' has no attribute 'pkg'
[ERROR   ] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'pkg'
[CRITICAL] Rendering SLS 'base:zabbix.frontend.conf' failed: Jinja variable 'dict object' has no attribute 'pkg'
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'local': ["Rendering SLS 'base:zabbix.server.conf' failed: Jinja variable 'dict object' has no attribute 'pkg'", "Rendering SLS 'base:zabbix.frontend.conf' failed: Jinja variable 'dict object' has no attribute 'pkg'"]}
```
I'm guessing the package names used to be saved in the map, but …
=> Hardcode names to correct for nonexistant pkg variables

zabbix/mysql/conf.sls
The current ordering of grant > user causes an issue:
```
----------
ID: zabbix_db
Function: mysql_grants.present
Result: False
Comment: An exception occurred in this state: Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1744, in call
**cdata['kwargs'])
File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1702, in wrapper
return f(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/salt/states/mysql_grants.py", line 191, in present
grant, database, user, host, grant_option, escape, ssl_option, **connection_args
File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 1776, in grant_add
_execute(cur, qry['qry'], qry['args'])
File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 547, in _execute
return …
```
=> Fix MySQL ordering

zabbix/files/default/etc/zabbix/zabbix_agentd.conf.jinja, zabbix/files/default/etc/zabbix/zabbix_proxy.conf.jinja
The comparison to zabbix.version_repo _happened_ to work if the value
in the pillar was a string. If the value in the pillar was not a string,
the comparison would fail. So here, we take version_repo, force it to a
float, and compare it to a float. In this way, it doesn't matter if the
repo value is '3.2' or 3.2; the comparison works correctly either way.
=> Be type agnostic when referencing version_repo

zabbix/agent/conf.sls, zabbix/agent/init.sls, zabbix/users.sls
Hello maintainers! 
The way the 'zabbix' user is created was changed [recently](https://github.com/saltstack-formulas/zabbix-formula/commit/e3e487e6ac233f8ed902d242141d4c316ab5527d).  I observed that on my Ubuntu (Xenial and Trusty) boxes & VMs, I would previously get a user with uid/gid in the low 100's, whereas I now end-up with a UID around 999 and GID of 1001 (+/- a few units).  This changed behaviour is a little unpleasant per se because it makes for discrepancies between machines but we'll leave the fix to this for the second commit because it's perhaps a little more subjective.
This first commit addresses the part which is almost certainly incorrect, namely that the UID of the created user is in the "system" range, whereas the GID isn't.
=> Fix zabbix user/group creation issues

pillar.example, zabbix/mysql/conf.sls
This fixes #52 by allowing alternative credentials to be provided (e.g. Amazon RDS)
=> Handle non-local database servers during provisioning

zabbix/repo.sls
Using it as it is throws an error on latest salt versions.
=> osmajorrelease is now an integer and no longer an array of strings

zabbix/agent/init.sls, zabbix/files/default/tmp/zabbix_agent.te, zabbix/files/default/tmp/zabbix_server.te, zabbix/server/init.sls
Allows the server and agent to start when run in selinux enforcing mode. Likely the server will require additional selinux perms in order to listen to a network socket.
=> Initial selinux handling

zabbix/map.jinja
This PR can be considered as as hotfix for #71.
#72 revealed (for me) serious flaw in my recent changes - #71 by default OS specific dict does not merge with 'default' dict, but just replace it. So if OS dict does not contain some key it will be unset, I think it's better that it will be set to default value. After all, the default values are created for this, to substitute what is missed.
Also this approach described in [template-formula](https://github.com/saltstack-formulas/template-formula/blob/5238913d6cb40ba4143963807e3c975144c7b8f4/template/map.jinja#L8)
This PR is important because after #71 all zabbix-agent defaults are stored in map.jinja and currently they only present for Debian. So zabbix_agent.conf will be generated improperly for all OS except Debian.
After this change OS …
=> Set 'default' as base in OS map

zabbix/agent/conf.sls, zabbix/agent/init.sls
On the first run, when the service is already started by the package installation, the formula fails to restart the agent saying that agent is already running and enabled.
This approach is similar to what apache-formula uses and it forces the agent to be restarted whenever the config changes.
https://github.com/saltstack-formulas/apache-formula/blob/master/apache/init.sls#L38
=> Fix agent not restarting when needed

zabbix/users.sls
Hello! Fix bugs plz!  Users must using uniq values!
remote:     Data failed to compile:
remote: ----------
remote:     Detected conflicting IDs, SLS IDs need to be globally unique.
remote:     The conflicting ID is 'zabbix_user' and is found in SLS 'base:users' and SLS 'base:zabbix.users'
=> uniq names for users.sls

zabbix/agent/conf.sls
After merging #10 `zabbix.agent.conf` became nonfunctional, this PR fixes it.
=> Fix requisite ID in zabbix.agent.conf introduced by #10

zabbix/files/default/tmp/zabbix_server_34.te, zabbix/frontend/init.sls, zabbix/server/init.sls
Zabbix 3.4 requires additional SELinux policies due to the introduction of inter-process communication using sockets.  This commit also enables the booleans to allow httpd (apache or nginx) to connect to zabbix and connect to the network.  If there are more secure settings that should be used instead of the booleans, I'd be glad to have the input.
=> Add SELinux policies for Zabbix 3.4 and SELinux booleans for httpd

pillar.example, zabbix/files/default/etc/zabbix/web/zabbix.conf.php.jinja, zabbix/frontend/conf.sls, zabbix/map.jinja
- Defaults moved to map.jinja
- More flexible states for frontend configuration file.
New version handle conditions when configuration file location different from `/etc/zabbix/web`. I.e. since version 3.0 default location is `/etc/zabbix`.
- 'dbpass' chaged to 'dbpassword', compatibility preserved.
=> Improvements for zabbix.frontend state

zabbix/agent/conf.sls, zabbix/agent/init.sls, zabbix/frontend/conf.sls, zabbix/frontend/init.sls, zabbix/proxy/conf.sls, zabbix/proxy/init.sls, zabbix/server/conf.sls, zabbix/server/init.sls
Create them manually as fallback.
- Order states in more logical manner
- More permanent code style
- 'settings' variable removed from zabbix.server and zabbix.proxy it is not used anywhere later in code.
=> Let package manager create user, group and directories

zabbix/agent/init.sls, zabbix/frontend/init.sls, zabbix/proxy/init.sls, zabbix/server/init.sls
Currently specifying version in lookup pillar does not work at all, because `pkg.installed` parameter `version` does not work if multiple packages supplied via `pkgs` parameter.
This PR fixes this bug.
=> Fixed version support for zabbix packages

README.rst, pillar.example, zabbix/map.jinja, zabbix/pgsql/conf.sls, zabbix/pgsql/schema.sls, zabbix/server/conf.sls
This PR add support of PostgreSQL version of Zabbix server to formula.
It's only tested with Zabbix version 3.4 but should work with 3.0+ and hopefully with upcoming v. 4 too. First of all I have no time to test and adapt for v. 2.0 - 2.2, and second I see no reason for that, I hope nobody will create new Zabbix installations with those old versions.
Main difference with MySQL part - instead of supply SQL schema with formula, SQL provided in package used.
=> Add PostgreSQL support

zabbix/users.sls
Make zabbix user group membership optional.
This allow the user to use the same pillar specification for servers running different services. E.g.:
zabbix:
user_groups:
- mysql
- named
- radiusd
The zabbix user will be added to the existing groups on each server and non-existing groups will be ignored.
=> Ignore non-existing groups

zabbix/files/default/etc/zabbix/zabbix_agentd.conf.jinja, zabbix/files/default/etc/zabbix/zabbix_proxy.conf.jinja, zabbix/map.jinja
As of today, the current LTS release is 4.0. So I took the chance to compare the current jinja Template against the default file for Debian 9 stretch from: "http://repo.zabbix.com/zabbix/4.0/debian/pool/main/z/zabbix/zabbix-proxy-sqlite3_4.0.3-1%2Bstretch_amd64.deb"
IMHO all the default comments should be completely added to the config file, to make it more understandable. And if I see it correctly, this is already the case for the Zabbix Agent jinja Template. 
I also added missing values for 4.0 with IF querys. 
I also added missing default values for Debian to the map.jinja.
=> Reworked jinja Template for Zabbix Proxy & Agent 4.0 LTS

zabbix/proxy/init.sls
My latest additions (https://github.com/saltstack-formulas/zabbix-formula/commit/ebf90ff56e37d2bf386d2760769c87767e0fa072#diff-de6a2fe5baab4590bf8f8ce616408d7e & https://github.com/saltstack-formulas/zabbix-formula/commit/0b0269c007e94e46e141f64482cdd0b1c1881257#diff-de6a2fe5baab4590bf8f8ce616408d7e) to handle include directory via a FOR loop messed up the "require" for the "service.running" part, as the service now won't start as the folders are created AFTER the "service.running" check. This bug makes the state fail on the very first execution, but it will work on every run after the first one. This commit fixes this.
=> BUGFIX: Zabbix proxy service requirement for include folder

README.rst, pillar.example, zabbix/agent/init.sls, zabbix/map.jinja
This addresses issue #112,  some requirements for this are having a salt windows repo setup and having a zabbix agent installer definition in that windows repo.  There is currently a pull request pending to add a zabbix-agent definition to the windows repo for the saltstack windows-ng repo
=> Add Windows Agent functionality

zabbix/proxy/init.sls, zabbix/repo.sls
As many people use SQLite for Zabbix proxy, I think it's obvious that the definition of a SQLite in the pillar database has to create the directory. I handled that in a separate state until now, but I find it odd that the official formula has to fail inevitable, because the Zabbix proxy daemon will never launch, because the directory is missing. 
But this pull request has a big drawback I think. I someone would like to use a real MySQL or MariaDB, this shouldn't be executed. 
I need some kind of IF statement, that will check if `dbname` contains a word or a path. I wasn't able to fix that yet. If we solve that, this will be a very helpful addition, as the formula will fail otherwise for all SQLite users.
=> Zabbix proxy sqlitedir - Need help

zabbix/repo.sls
@aboe76 I'm very sorry, I must have made a mistake, the "apt-transport-https" was added, but not the URL change.
=> Switch Debian apt repo to https (2nd try)

.travis.yml
* Automated using https://github.com/myii/ssf-formula/pull/67
=> ci(travis): use `fedora-29` instead of `fedora-30` (for reliability)

zabbix/files/default/etc/zabbix/zabbix_proxy.conf.jinja
---
No.
Related to #83
Use `dbapssword` instead of `dbpass` in zabbix-proxy template file. Even though MySQL / PostgreSQL versions of zabbix-proxy is not supported by this formula consistent variable naming across formula would be useful in future.
Not required. This changes if for "future use".
N/A
=> refactor: Use dbapssword consistently across formula

zabbix/agent/init.sls
Potentially.
Currently all the examples seem to end with "/" if it's an directory, so should work. If user creates an include "/path/to/an/directory", it will only create "/path/to/an/", as it doesn't have a way to determine it better, than the slash at the end.
https://github.com/saltstack-formulas/zabbix-formula/issues/111
Strip the filename or glob at the end of the path, if it's not a directory
try with both a directory (ending in "/") and a file-like path in agent includes, i did with
zabbix:
lookup:
agent:
includes:
- /etc/zabbix/zabbix_agent2.d/*.conf
- /tmp/test/
----------
ID: /etc/zabbix/zabbix_agent2.d/*.conf
Function: file.directory
Name: /etc/zabbix/zabbix_agent2.d
Result: True
Comment: The directory /etc/zabbix/zabbix_agent2.d is in the correct state
Started: 22:48:22.035102 …
=> When creating directory that is included from agent config, strip filename or glob at the end

.gitlab-ci.yml, test/integration/default/controls/config_spec.rb, zabbix/agent/repo.sls, zabbix/frontend/repo.sls, zabbix/osfamilymap.yaml, zabbix/osfingermap.yaml, zabbix/proxy/repo.sls, zabbix/repo.sls, zabbix/server/repo.sls
No.
Replaces https://github.com/saltstack-formulas/zabbix-formula/pull/140
Following up on my colleagues work from https://github.com/saltstack-formulas/zabbix-formula/pull/140 i made adjustments to the defaults to go with mysql as you prefer. Please let me know if there are any other issues i did not address properly.
=> Add suse support (with mysql defaults this time)

zabbix/files/default/etc/zabbix/zabbix_proxy.conf.jinja
---
No.
Reworked jinja Template for Zabbix Proxy 5.0 LTS
=> feat(proxy_conf): Reworked jinja Template for Zabbix Proxy 5.0 LTS

zabbix/files/default/etc/zabbix/zabbix_proxy.conf.jinja
---
No.
When `starthttppollers` is set for a Zabbix proxy, it incorrectly tries to setup the `javagateway` settings. This fixes the template to correctly use `javagateway` in the check before trying to setup the Java pollers.
=> Fix bug in javagateway on zabbix proxies

zabbix/files/default/etc/zabbix/zabbix_proxy.conf.jinja
---
No.
Reworked jinja Template for Zabbix Proxy 6.0 LTS
=> feat(proxy_conf): Reworked jinja Template for Zabbix Proxy 6.0 LTS

zabbix/osfingermap.yaml
=> fix(repo): add repo config for Ubuntu-24.04

pillar.example, zabbix/defaults.yaml, zabbix/files/default/etc/zabbix/web/zabbix.conf.php.jinja
---
No.
Zabbix 5.0 will complain in froentend with "Database history tables upgraded | No" unless a variable is set ij web connfig file. Unfortunately upgrading the tables is not enough, it needs to be told in config too. This should be done in pillar when upgrading.
```
zabbix:
lookup:
version_repo: 5.4
frontend:
historyupgraded: true
```
```
ID: /etc/zabbix/web/zabbix.conf.php
Function: file.managed
Result: True
Comment: File /etc/zabbix/web/zabbix.conf.php updated
Started: 14:52:25.967616
Duration: 224.967 ms
Changes:   
----------
diff:
--- 
+++ 
@@ -16,4 +16,5 @@
$ZBX_SERVER_NAME             = 'Zabbix installed with SaltStack';
$IMAGE_FORMAT_DEFAULT        = IMAGE_FORMAT_PNG;
+$DB['DOUBLE_IEEE754'] = 'true';
?>
```
=> feat(frontend): allow to set that db history tables were updated (zabbix 5.0+)
